export const data = [
  {
    id: 1,
    name: "Morgan Silver Dollar",
    year: 1884,
    country: "United States",
    value: 100.0,
    material: "Silver",
    condition: "Very Fine",
  },
  {
    id: 2,
    name: "Gold Sovereign",
    year: 1911,
    country: "United Kingdom",
    value: 500.0,
    material: "Gold",
    condition: "Mint",
  },
  {
    id: 3,
    name: "Canadian Silver Maple Leaf",
    year: 1988,
    country: "Canada",
    value: 25.0,
    material: "Silver",
    condition: "Mint",
  },
  {
    id: 4,
    name: "Peace Dollar",
    year: 1922,
    country: "United States",
    value: 150.0,
    material: "Silver",
    condition: "Fine",
  },
  {
    id: 5,
    name: "Austrian Gold Ducat",
    year: 1915,
    country: "Austria",
    value: 200.0,
    material: "Gold",
    condition: "Very Fine",
  },
  {
    id: 6,
    name: "Chinese Silver Panda",
    year: 2015,
    country: "China",
    value: 30.0,
    material: "Silver",
    condition: "Mint",
  },
  {
    id: 7,
    name: "French Napoleon III 20 Franc",
    year: 1854,
    country: "France",
    value: 300.0,
    material: "Gold",
    condition: "Good",
  },
  {
    id: 8,
    name: "South African Krugerrand",
    year: 1967,
    country: "South Africa",
    value: 400.0,
    material: "Gold",
    condition: "Mint",
  },
  {
    id: 9,
    name: "Liberty Head Nickel",
    year: 1883,
    country: "United States",
    value: 120.0,
    material: "Nickel",
    condition: "Fine",
  },
  {
    id: 10,
    name: "Mexican 50 Peso Gold Coin",
    year: 1947,
    country: "Mexico",
    value: 1000.0,
    material: "Gold",
    condition: "Mint",
  },
];